### ISSUE TITLE
Update from ga.js to analytics.js

### ISSUE THREAD

**Issue by iteles** [dwyl/dwyl.github.io#19]
When the site moves out of alpha! https://developers.google.com/analytics/devguides/collection/gajs/

**Comment by iteles** [comment]
Currently investigation whether to [just use analytics.js or go for the Google Tag Manager container](https://developers.google.com/analytics/devguides/collection/upgrade/reference/gtm)

**Comment by nelsonic** [comment]
So *glad* you #***finally*** learning this... Brings back *many memories* of #**2010** :stuck_out_tongue_winking_eye:

**Comment by iteles** [comment]
Nice.

**Comment by iteles** [comment]
Decided against going full-blown Google Tag Manager for now (don't see the need) and ensured script is analytics.js and loading asynchronously for modern browsers ([actually understanding how it works](https://developers.google.com/analytics/devguides/collection/analyticsjs/#alternative_async_tracking_snippet)).

**Comment by nelsonic** [comment]
You made the *right* decision... :wink: 
Cannot *stand* Google Tag Manager. Its one of those "*necessary evils*" that developers put up with, but is slow and clunky.

**Comment by iteles** [comment]
You could have been _this_ helpful an hour ago :laughing:

**Comment by nelsonic** [comment]
You didn't *ask* me...

**Comment by iteles** [comment]
If I'm _investigating_ something you already know the answer to...

**Comment by nelsonic** [comment]
Direct questions are betterer.
I'm *used* to people at FAC ignoring anything I've written/said so I just keep quiet...

**Comment by nelsonic** [comment]
If you *ask* me what I would recommend you *focus* on... the answer is: https://mixpanel.com

**Comment by iteles** [comment]
Ooooooooh...!

**Comment by nelsonic** [comment]
If you read what I *write* you would know we are using [***Kibana***](https://github.com/nelsonic/learn-kibana) for our app because we are *already* storing our data in ElasticSearch which means it is *not* being sent to a third party where we have *zero* control over it. 
The *plan* is to build a simplified application-specific usage tracker. 
Setting up analytics *properly* on MixPanel takes *just* as much work as writing our own event handler and pushing the data into ES. if you ask me I will tell you *exactly* what to do.

**Comment by iteles** [comment]
:+1: #transferableconcepts
